services:
  db:
    image: postgres:15-alpine
    container_name: pandoragym_db
    environment:
      POSTGRES_DB: pandoragym_db
      POSTGRES_USER: pandoragym
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pandoragym -d pandoragym_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - pandoragym-network

  app:
    build: .
    container_name: pandoragym_app
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://pandoragym:password@db:5432/pandoragym_db?sslmode=disable
      - PORT=3333
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - SUPABASE_URL=https://your-project.supabase.co
      - SUPABASE_ANON_KEY=your-supabase-anon-key
      - SUPABASE_SERVICE_ROLE_KEY=your-supabase-service-role-key
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - app_tmp:/app/tmp  # Air temp directory
    working_dir: /app
    command: air -c .air.toml
    restart: unless-stopped
    networks:
      - pandoragym-network

volumes:
  postgres_data:
    name: pandoragym_postgres_data
  app_tmp:
    name: pandoragym_go_app

networks:
  pandoragym-network:
    name: pandoragym_network
    driver: bridge
