version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: pandoragym_db
      POSTGRES_USER: pandoragym
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pandoragym -d pandoragym_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build: .
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=pandoragym_db
      - DATABASE_USER=pandoragym
      - DATABASE_PASSWORD=password
      - DATABASE_URL=postgresql://pandoragym:password@db:5432/pandoragym_db?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    command: go run ./cmd/tern
    restart: "no"

  seed:
    build: .
    environment:
      - DATABASE_URL=postgresql://pandoragym:password@db:5432/pandoragym_db?sslmode=disable
    depends_on:
      - migrate
    volumes:
      - .:/app
    working_dir: /app
    command: go run ./cmd/seed
    restart: "no"

  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://pandoragym:password@db:5432/pandoragym_db?sslmode=disable
      - PORT=3333
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - SUPABASE_URL=https://your-project.supabase.co
      - SUPABASE_ANON_KEY=your-supabase-anon-key
      - SUPABASE_SERVICE_ROLE_KEY=your-supabase-service-role-key
    depends_on:
      - seed
    volumes:
      - .:/app
    working_dir: /app
    command: go run cmd/server/main.go
    restart: unless-stopped

volumes:
  postgres_data:
